#!/bin/bash
GRINDERPATH=$COMMON_HOME/grinder
GRINDERPROPERTIES=$GRINDERPATH/grinder.properties
CLASSPATH=$GRINDERPATH/lib/*.jar:$CLASSPATH
export CLASSPATH PATH GRINDERPROPERTIES
java -cp $CLASSPATH net.grinder.Grinder  $GRINDERPROPERTIES
